# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since_id', models.IntegerField()),
                ('tweet_text', models.CharField(max_length=200)),
                ('tweet_urls', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='tweets',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.UsersInfo'),
        ),
    ]
