# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name_plural': 'Tweets'},
        ),
        migrations.AlterModelOptions(
            name='usersinfo',
            options={'verbose_name_plural': 'UsersInfo'},
        ),
    ]
