# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20170824_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('oauth_secret', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('oauth_token', models.CharField(max_length=100)),
            ],
        ),
    ]
