# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_secret', models.CharField(max_length=100)),
                ('oauth_token', models.CharField(max_length=100)),
            ],
        ),
    ]
