# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProToken',
        ),
    ]
