# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20170825_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protoken',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='protoken',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 0, 43, 10, 196505)),
        ),
    ]
