# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20170826_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protoken',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
