# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_auto_20170826_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protoken',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
