# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20170826_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protoken',
            options={'ordering': ['-time']},
        ),
    ]
