# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_auto_20170826_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='protoken',
            name='id',
        ),
        migrations.RemoveField(
            model_name='protoken',
            name='time',
        ),
        migrations.AddField(
            model_name='protoken',
            name='user_id',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protoken',
            name='user_name',
            field=models.CharField(default='sam', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.ProToken'),
        ),
        migrations.DeleteModel(
            name='UsersInfo',
        ),
    ]
