# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20170826_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ['-since_id'], 'verbose_name_plural': 'Tweets'},
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='tweet_text',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='tweet_urls',
        ),
        migrations.AddField(
            model_name='tweets',
            name='json_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
