# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20170826_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='protoken',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protoken',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
