# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_auto_20170826_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='user_id',
            field=models.IntegerField(default=100),
        ),
    ]
