# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_auto_20170826_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='id',
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.TwitterUser'),
        ),
    ]
