# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_auto_20170826_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertweet',
            name='date',
            field=models.DateTimeField(default=datetime.date(2017, 8, 26), verbose_name=datetime.date(2017, 8, 26)),
        ),
    ]
