# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0020_auto_20170826_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweet',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name=datetime.date(2017, 8, 26)),
        ),
    ]
