# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_auto_20170826_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
