# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 11:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_auto_20170826_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweet',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2017, 8, 26)),
        ),
    ]
