# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0024_auto_20170826_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertweet',
            name='date',
        ),
        migrations.AddField(
            model_name='usertweet',
            name='created_at',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='day',
            field=models.IntegerField(default=27),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='month',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='screen_name_tweet',
            field=models.CharField(default='unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='text',
            field=models.CharField(default='', max_length=170),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='urls',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usertweet',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
